stages:
  - postman
  
postman_job:
  stage: postman
  before_script:
  - npm install npm@latest
  - npm install newman
  - npm cache clean
  - npm install newman-reporter-htmlextra
  
  script:
  - npm run test
